// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpmydjijulqsalhildbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwbXlkamlqdWxxc2FsaGlsZGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NjMzMTcsImV4cCI6MjA1MzIzOTMxN30.XwAysr64ok_CgWngNBjWOmgW1ZP1dO_KIPoBHgo0c7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);